### ISSUE TITLE
stored values in config.json get reset at app's start

### ISSUE THREAD

**Issue by Developer-Simon** [sindresorhus/electron-store#154] opened 2020-12-06 12:29 UTC
I thought it would be the advantage of this lib, that the data I store will be persistent. But every time I start my application the whole values in the config file are set to default. I didn't find out any comments on that in the description, so my question is: did i some mistakes in configuration or is this supposed to work like that? 

Cheers
Simon

**Comment by sindresorhus** [comment] 2020-12-07 03:49
Duplicate of #86

**Comment by sindresorhus** [comment] 2020-12-07 03:50
You'll want to set this option: https://github.com/sindresorhus/electron-store#clearinvalidconfig

**Closed by sindresorhus** 2020-12-07 03:49 UTC

**Comment by Developer-Simon** [comment] 2020-12-07 12:27
Mmh, i already tried out that option in initialization. Nevertheless it changes my stored 1 to 0 every time i start my program.
