### ISSUE TITLE
Unable to use in Electron 10+

### ISSUE THREAD

**Issue by walmat** [sindresorhus/electron-store#141] opened 2020-09-06 22:40 UTC
Hi, due to Electron's aim to deprecate the remote module, we are unable to use this library for any project using Electron 10+.

The culprit is [here](https://github.com/sindresorhus/electron-store/blob/f4673e0f30668e49658e332307cc1443cc1c3818/index.js#L8), however, maybe there are more checks similar to this in the repo.

[Here](https://github.com/electron/electron/pull/22091) is the issue referencing the deprecation plans.

Please let me know if there is anything I can do to provide assistance as most of my projects rely heavily on this library.

**Comment by sindresorhus** [comment] 2020-09-06 23:01
Duplicate of https://github.com/sindresorhus/electron-store/issues/140

**Closed by sindresorhus** 2020-09-06 23:01 UTC
