### ISSUE TITLE
TypeScript errors with electron-store methods, but app works fine

### ISSUE THREAD

**Issue by only-issues** [sindresorhus/electron-store#281] opened 2024-09-12 11:31 UTC
I'm using [electron-vite](https://github.com/alex8088/electron-vite) and encountering TypeScript errors with electron-store, specifically with methods like `set`, `get`, and `delete`. However, the application runs without any errors and functions correctly.

Error message example:
TS2339: Property 'set' does not exist on type 'ElectronStore<Record<string, unknown>>'.

Similar errors occur for other methods like `get` and `delete`.

My setup:
- electron-vite
- TypeScript
- electron-store

Code snippet:

```typescript
import Store from 'electron-store';

const store = new Store();
store.set('theme', 'dark'); // TypeScript error here
console.log(store.get('theme')); // TypeScript error here
// Output: dark
```
![image](https://github.com/user-attachments/assets/76bd67a1-a4ca-46d1-a5e0-5733588574b1)
![image](https://github.com/user-attachments/assets/7326b59c-7c4f-4d0f-afe7-c48a3962482b)

**Comment by sindresorhus** [comment] 2024-09-12 11:47
Duplicate of #276

**Closed by sindresorhus** 2024-09-12 11:47 UTC
