### ISSUE TITLE
Cannot find module "."

### ISSUE THREAD

**Issue by guoyunhe** [sindresorhus/electron-store#24] opened 2017-10-05 17:14 UTC
```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (index.js:25)
    at ElectronStore.Conf (index.js:25)
    at ElectronStore (index.js:20)
    at Object../app/actions/recent-projects.js (recent-projects.js:4)
    at __webpack_require__ (bootstrap 92e2fd3…:677)
    at fn (bootstrap 92e2fd3…:87)
    at Object../app/containers/HomePage.js (HomePage.js:8)
    at __webpack_require__ (bootstrap 92e2fd3…:677)
    at fn (bootstrap 92e2fd3…:87)
    at Object../app/routes.js (routes.js:5)
```

Have this error in one of my project. Unluckily, I cannot provide the source code.

**Comment by sindresorhus** [comment] 2017-10-05 17:33
Duplicate of https://github.com/sindresorhus/electron-store/issues/3

**Comment by sindresorhus** [comment] 2017-10-05 17:33
It's up to you to handle Webpack issues.

**Closed by sindresorhus** 2017-10-05 17:33 UTC
