### ISSUE TITLE
Uncaught TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by sinmineryt** [sindresorhus/electron-store#161] opened 2021-01-12 16:23 UTC
When creating a new store like this:
```js
const store = new Store();
```
an error gets thrown:
```
Uncaught TypeError: Cannot read property 'app' of undefined
    at new ElectronStore (C:\projects\electron_app\node_modules\electron-store\index.js:8)
    at storage.js:4
```

**Comment by sindresorhus** [comment] 2021-01-12 16:38
Duplicate of #152

**Closed by sindresorhus** 2021-01-12 16:38 UTC
