### ISSUE TITLE
rollup bundling: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by pjebs** [sindresorhus/electron-store#98] opened 2020-01-17 11:58 UTC
After I bundle my codebase using rollup and then run the electron app, I get this error:

```
App threw an error during load
TypeError: Cannot convert undefined or null to object
    at /Users/xx/Developer/zz/desktop-app/app/main.js:78:136539
    at w (/Users/xx/Developer/zz/desktop-app/app/main.js:64:807)
    at /Users/xx/Developer/zz/desktop-app/app/main.js:78:136477
    at Object.<anonymous> (/Users/xx/Developer/zz/desktop-app/app/main.js:96:5)
    at Object.<anonymous> (/Users/xx/Developer/zz/desktop-app/app/main.js:104:4)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at loadApplicationPackage (/Users/xx/Developer/zz/desktop-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:109:16)
    at Object.<anonymous> (/Users/xx/Developer/zz/desktop-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:9)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5709:12)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5716:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:302:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:630:15)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11
```

When I comment out `Store: require('electron-store')` and comment out where I use it, the app loads fine after bundling.

Is anyone else getting this issue?

**Comment by pjebs** [comment] 2020-01-17 12:07
When I don't bundle, it works perfectly.

**Comment by sindresorhus** [comment] 2020-01-17 13:52
Duplicate of #97

**Comment by sindresorhus** [comment] 2020-01-17 13:52
This is not really the place to ask about Rollup support.

**Closed by sindresorhus** 2020-01-17 13:52 UTC
