### ISSUE TITLE
Electron-store data folders

### ISSUE THREAD

**Issue by WebbyNFT** [sindresorhus/electron-store#235] opened 2022-09-05 20:39 UTC
Hi,
I defined my store as `const store = new Store({ name: 'MyAppName' });`. 

When I run my app by `yarn start` and save any data to store it is not saved into `~/Library/Application Support/MyAppName`. It works only when I package app and run executable file. 

So my question is where is this data stored on my Mac? Looks like it is different folder for development and different after packaging app into executable file.

If I log `app.getPath('appData')` for both I see `~/Library/Application Support/MyAppName` but I have different data after running `yarn start` and different after `yarn package` and  running executable file.

**Comment by sindresorhus** [comment] 2022-09-06 02:57
Duplicate of #233

**Closed by sindresorhus** 2022-09-06 02:57 UTC

**Comment by WebbyNFT** [comment] 2022-09-19 13:58
For all people interested in, when you run electron in development mode all data is stored in `Electron` folder. If you build your project all data is stored in the name that you define when creating store.
