### ISSUE TITLE
error in render process

### ISSUE THREAD

**Issue by 673800357** [sindresorhus/electron-store#27] opened 2017-10-25 12:48 UTC
I see the docs says that the module can use in both render and main process,but i use the module in main process,it seems to have some error.How can use the module in render process?
![b1](https://user-images.githubusercontent.com/20512530/31999505-09873580-b9c6-11e7-9c2f-dc51c735a8f5.png)
![b2](https://user-images.githubusercontent.com/20512530/31999504-094e8500-b9c6-11e7-892c-e823df79a39f.png)

**Comment by bonavida** [comment] 2017-10-25 16:06
You can use the module in renderer process the same way you use it in main process. I guess you already imported the module with require on the renderer process. Anyway, it would be really helpful to see the rest of the code, if you don't mind.

**Comment by 673800357** [comment] 2017-10-26 04:31
![bb2](https://user-images.githubusercontent.com/20512530/32035122-86c0233a-ba49-11e7-8229-060f28d99c64.png)

![bb1](https://user-images.githubusercontent.com/20512530/32035120-818834d4-ba49-11e7-9a0e-baf1da2b3018.png)
@bonavida  The rest of my  code has nothing correlation. I just copy the demo code in my file entry.I am sure that i have not required the module  on other way. You can the image below. Thanks

**Comment by sonnyg** [comment] 2017-10-26 15:22
It looks like the electron-store module is not included in your webpack bundle. 

...at webpackMissingModule (index.js:25)

Given that this error is occurring in the renderer process, it seems all the more likely.

**Comment by sindresorhus** [comment] 2017-11-07 05:50
Duplicate of #3

**Closed by sindresorhus** 2017-11-07 05:50 UTC
